// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "csdeft.h"

/////////////////////////////////////////////////////////////////////////////
// CCsdEft

IMPLEMENT_DYNCREATE(CCsdEft, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCsdEft properties

CString CCsdEft::GetResponseText()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetResponseText(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

CString CCsdEft::GetResponseCode()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetResponseCode(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

CString CCsdEft::GetTxnType()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetTxnType(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

long CCsdEft::GetStan()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetStan(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

CString CCsdEft::GetPanSource()
{
	CString result;
	GetProperty(0x5, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPanSource(LPCTSTR propVal)
{
	SetProperty(0x5, VT_BSTR, propVal);
}

CString CCsdEft::GetPan()
{
	CString result;
	GetProperty(0x6, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPan(LPCTSTR propVal)
{
	SetProperty(0x6, VT_BSTR, propVal);
}

CString CCsdEft::GetNii()
{
	CString result;
	GetProperty(0x7, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetNii(LPCTSTR propVal)
{
	SetProperty(0x7, VT_BSTR, propVal);
}

long CCsdEft::GetMerchant()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetMerchant(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

CString CCsdEft::GetTrack2()
{
	CString result;
	GetProperty(0x9, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetTrack2(LPCTSTR propVal)
{
	SetProperty(0x9, VT_BSTR, propVal);
}

CString CCsdEft::GetTrack1()
{
	CString result;
	GetProperty(0xa, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetTrack1(LPCTSTR propVal)
{
	SetProperty(0xa, VT_BSTR, propVal);
}

long CCsdEft::GetDialogX()
{
	long result;
	GetProperty(0xb, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetDialogX(long propVal)
{
	SetProperty(0xb, VT_I4, propVal);
}

long CCsdEft::GetDialogY()
{
	long result;
	GetProperty(0xc, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetDialogY(long propVal)
{
	SetProperty(0xc, VT_I4, propVal);
}

CString CCsdEft::GetDateSettlement()
{
	CString result;
	GetProperty(0xd, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetDateSettlement(LPCTSTR propVal)
{
	SetProperty(0xd, VT_BSTR, propVal);
}

CString CCsdEft::GetDialogType()
{
	CString result;
	GetProperty(0xe, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetDialogType(LPCTSTR propVal)
{
	SetProperty(0xe, VT_BSTR, propVal);
}

CString CCsdEft::GetAccountType()
{
	CString result;
	GetProperty(0xf, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetAccountType(LPCTSTR propVal)
{
	SetProperty(0xf, VT_BSTR, propVal);
}

CString CCsdEft::GetTxnRef()
{
	CString result;
	GetProperty(0x10, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetTxnRef(LPCTSTR propVal)
{
	SetProperty(0x10, VT_BSTR, propVal);
}

CString CCsdEft::GetPinPadVersion()
{
	CString result;
	GetProperty(0x11, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPinPadVersion(LPCTSTR propVal)
{
	SetProperty(0x11, VT_BSTR, propVal);
}

CString CCsdEft::GetPinPadSerialNumber()
{
	CString result;
	GetProperty(0x12, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPinPadSerialNumber(LPCTSTR propVal)
{
	SetProperty(0x12, VT_BSTR, propVal);
}

CString CCsdEft::GetDataField()
{
	CString result;
	GetProperty(0x13, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetDataField(LPCTSTR propVal)
{
	SetProperty(0x13, VT_BSTR, propVal);
}

CString CCsdEft::GetReceipt()
{
	CString result;
	GetProperty(0x14, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetReceipt(LPCTSTR propVal)
{
	SetProperty(0x14, VT_BSTR, propVal);
}

long CCsdEft::GetTimeout()
{
	long result;
	GetProperty(0x15, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetTimeout(long propVal)
{
	SetProperty(0x15, VT_I4, propVal);
}

BOOL CCsdEft::GetConfigLocked()
{
	BOOL result;
	GetProperty(0x16, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetConfigLocked(BOOL propVal)
{
	SetProperty(0x16, VT_BOOL, propVal);
}

BOOL CCsdEft::GetCutReceipt()
{
	BOOL result;
	GetProperty(0x17, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetCutReceipt(BOOL propVal)
{
	SetProperty(0x17, VT_BOOL, propVal);
}

BOOL CCsdEft::GetLoggedOn()
{
	BOOL result;
	GetProperty(0x18, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetLoggedOn(BOOL propVal)
{
	SetProperty(0x18, VT_BOOL, propVal);
}

CString CCsdEft::GetDateExpiry()
{
	CString result;
	GetProperty(0x19, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetDateExpiry(LPCTSTR propVal)
{
	SetProperty(0x19, VT_BSTR, propVal);
}

CY CCsdEft::GetTotalPurchase()
{
	CY result;
	GetProperty(0x1a, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetTotalPurchase(const CY& propVal)
{
	SetProperty(0x1a, VT_CY, &propVal);
}

CY CCsdEft::GetTotalCash()
{
	CY result;
	GetProperty(0x1b, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetTotalCash(const CY& propVal)
{
	SetProperty(0x1b, VT_CY, &propVal);
}

CY CCsdEft::GetTotalRefund()
{
	CY result;
	GetProperty(0x1c, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetTotalRefund(const CY& propVal)
{
	SetProperty(0x1c, VT_CY, &propVal);
}

long CCsdEft::GetTotalPurchaseCount()
{
	long result;
	GetProperty(0x1d, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetTotalPurchaseCount(long propVal)
{
	SetProperty(0x1d, VT_I4, propVal);
}

long CCsdEft::GetTotalCashCount()
{
	long result;
	GetProperty(0x1e, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetTotalCashCount(long propVal)
{
	SetProperty(0x1e, VT_I4, propVal);
}

long CCsdEft::GetTotalRefundCount()
{
	long result;
	GetProperty(0x1f, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetTotalRefundCount(long propVal)
{
	SetProperty(0x1f, VT_I4, propVal);
}

CString CCsdEft::GetCaid()
{
	CString result;
	GetProperty(0x20, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCaid(LPCTSTR propVal)
{
	SetProperty(0x20, VT_BSTR, propVal);
}

CString CCsdEft::GetCatid()
{
	CString result;
	GetProperty(0x21, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCatid(LPCTSTR propVal)
{
	SetProperty(0x21, VT_BSTR, propVal);
}

BOOL CCsdEft::GetSuccess()
{
	BOOL result;
	GetProperty(0x22, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetSuccess(BOOL propVal)
{
	SetProperty(0x22, VT_BOOL, propVal);
}

CString CCsdEft::GetDate()
{
	CString result;
	GetProperty(0x23, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetDate(LPCTSTR propVal)
{
	SetProperty(0x23, VT_BSTR, propVal);
}

CString CCsdEft::GetTime()
{
	CString result;
	GetProperty(0x24, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetTime(LPCTSTR propVal)
{
	SetProperty(0x24, VT_BSTR, propVal);
}

BOOL CCsdEft::GetEnableTip()
{
	BOOL result;
	GetProperty(0x25, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetEnableTip(BOOL propVal)
{
	SetProperty(0x25, VT_BOOL, propVal);
}

long CCsdEft::GetResponseType()
{
	long result;
	GetProperty(0x26, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetResponseType(long propVal)
{
	SetProperty(0x26, VT_I4, propVal);
}

CString CCsdEft::GetChqSerialNumber()
{
	CString result;
	GetProperty(0x27, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetChqSerialNumber(LPCTSTR propVal)
{
	SetProperty(0x27, VT_BSTR, propVal);
}

CString CCsdEft::GetChqBranch()
{
	CString result;
	GetProperty(0x28, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetChqBranch(LPCTSTR propVal)
{
	SetProperty(0x28, VT_BSTR, propVal);
}

CString CCsdEft::GetChqAccount()
{
	CString result;
	GetProperty(0x29, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetChqAccount(LPCTSTR propVal)
{
	SetProperty(0x29, VT_BSTR, propVal);
}

CString CCsdEft::GetDialogPosition()
{
	CString result;
	GetProperty(0x2a, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetDialogPosition(LPCTSTR propVal)
{
	SetProperty(0x2a, VT_BSTR, propVal);
}

long CCsdEft::GetMessageType()
{
	long result;
	GetProperty(0x2b, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetMessageType(long propVal)
{
	SetProperty(0x2b, VT_I4, propVal);
}

CString CCsdEft::GetEftposNetwork()
{
	CString result;
	GetProperty(0x2c, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetEftposNetwork(LPCTSTR propVal)
{
	SetProperty(0x2c, VT_BSTR, propVal);
}

BOOL CCsdEft::GetPrintJournal()
{
	BOOL result;
	GetProperty(0x2d, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetPrintJournal(BOOL propVal)
{
	SetProperty(0x2d, VT_BOOL, propVal);
}

CString CCsdEft::GetPosVendor()
{
	CString result;
	GetProperty(0x2e, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPosVendor(LPCTSTR propVal)
{
	SetProperty(0x2e, VT_BSTR, propVal);
}

CString CCsdEft::GetPosProductId()
{
	CString result;
	GetProperty(0x2f, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPosProductId(LPCTSTR propVal)
{
	SetProperty(0x2f, VT_BSTR, propVal);
}

CString CCsdEft::GetPosVersion()
{
	CString result;
	GetProperty(0x30, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPosVersion(LPCTSTR propVal)
{
	SetProperty(0x30, VT_BSTR, propVal);
}

CString CCsdEft::GetLicenseId()
{
	CString result;
	GetProperty(0x31, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetLicenseId(LPCTSTR propVal)
{
	SetProperty(0x31, VT_BSTR, propVal);
}

CY CCsdEft::GetSettleTotal()
{
	CY result;
	GetProperty(0x32, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetSettleTotal(const CY& propVal)
{
	SetProperty(0x32, VT_CY, &propVal);
}

CY CCsdEft::GetSettleTotalDebit()
{
	CY result;
	GetProperty(0x33, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetSettleTotalDebit(const CY& propVal)
{
	SetProperty(0x33, VT_CY, &propVal);
}

CY CCsdEft::GetSettleTotalCredit()
{
	CY result;
	GetProperty(0x34, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetSettleTotalCredit(const CY& propVal)
{
	SetProperty(0x34, VT_CY, &propVal);
}

BOOL CCsdEft::GetReceiptAutoPrint()
{
	BOOL result;
	GetProperty(0x35, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetReceiptAutoPrint(BOOL propVal)
{
	SetProperty(0x35, VT_BOOL, propVal);
}

CString CCsdEft::GetCardType()
{
	CString result;
	GetProperty(0x36, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCardType(LPCTSTR propVal)
{
	SetProperty(0x36, VT_BSTR, propVal);
}

BOOL CCsdEft::GetReady()
{
	BOOL result;
	GetProperty(0x37, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetReady(BOOL propVal)
{
	SetProperty(0x37, VT_BOOL, propVal);
}

BOOL CCsdEft::GetInstalled()
{
	BOOL result;
	GetProperty(0x38, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetInstalled(BOOL propVal)
{
	SetProperty(0x38, VT_BOOL, propVal);
}

long CCsdEft::GetVersionMajor()
{
	long result;
	GetProperty(0x39, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetVersionMajor(long propVal)
{
	SetProperty(0x39, VT_I4, propVal);
}

long CCsdEft::GetVersionMinor()
{
	long result;
	GetProperty(0x3a, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetVersionMinor(long propVal)
{
	SetProperty(0x3a, VT_I4, propVal);
}

long CCsdEft::GetVersionRevision()
{
	long result;
	GetProperty(0x3b, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetVersionRevision(long propVal)
{
	SetProperty(0x3b, VT_I4, propVal);
}

BOOL CCsdEft::GetEnableErrorDialog()
{
	BOOL result;
	GetProperty(0x3c, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetEnableErrorDialog(BOOL propVal)
{
	SetProperty(0x3c, VT_BOOL, propVal);
}

CString CCsdEft::GetFilename()
{
	CString result;
	GetProperty(0x3d, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetFilename(LPCTSTR propVal)
{
	SetProperty(0x3d, VT_BSTR, propVal);
}

CString CCsdEft::GetAiic()
{
	CString result;
	GetProperty(0x3e, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetAiic(LPCTSTR propVal)
{
	SetProperty(0x3e, VT_BSTR, propVal);
}

CY CCsdEft::GetSettleTotalPurchase()
{
	CY result;
	GetProperty(0x3f, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetSettleTotalPurchase(const CY& propVal)
{
	SetProperty(0x3f, VT_CY, &propVal);
}

CY CCsdEft::GetSettleTotalRefund()
{
	CY result;
	GetProperty(0x40, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetSettleTotalRefund(const CY& propVal)
{
	SetProperty(0x40, VT_CY, &propVal);
}

CString CCsdEft::GetAuthCode()
{
	CString result;
	GetProperty(0x41, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetAuthCode(LPCTSTR propVal)
{
	SetProperty(0x41, VT_BSTR, propVal);
}

BOOL CCsdEft::GetLastTxnSuccess()
{
	BOOL result;
	GetProperty(0x42, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetLastTxnSuccess(BOOL propVal)
{
	SetProperty(0x42, VT_BOOL, propVal);
}

CY CCsdEft::GetSettleTotalCash()
{
	CY result;
	GetProperty(0x43, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetSettleTotalCash(const CY& propVal)
{
	SetProperty(0x43, VT_CY, &propVal);
}

CString CCsdEft::GetSettleCardTotals()
{
	CString result;
	GetProperty(0x44, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCardTotals(LPCTSTR propVal)
{
	SetProperty(0x44, VT_BSTR, propVal);
}

long CCsdEft::GetSettleCountCash()
{
	long result;
	GetProperty(0x45, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCountCash(long propVal)
{
	SetProperty(0x45, VT_I4, propVal);
}

long CCsdEft::GetSettleCount()
{
	long result;
	GetProperty(0x46, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCount(long propVal)
{
	SetProperty(0x46, VT_I4, propVal);
}

long CCsdEft::GetSettleCountCredit()
{
	long result;
	GetProperty(0x47, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCountCredit(long propVal)
{
	SetProperty(0x47, VT_I4, propVal);
}

long CCsdEft::GetSettleCountDebit()
{
	long result;
	GetProperty(0x48, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCountDebit(long propVal)
{
	SetProperty(0x48, VT_I4, propVal);
}

long CCsdEft::GetSettleCountPurchase()
{
	long result;
	GetProperty(0x49, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCountPurchase(long propVal)
{
	SetProperty(0x49, VT_I4, propVal);
}

long CCsdEft::GetSettleCountRefund()
{
	long result;
	GetProperty(0x4a, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCountRefund(long propVal)
{
	SetProperty(0x4a, VT_I4, propVal);
}

BOOL CCsdEft::GetEnableManualPan()
{
	BOOL result;
	GetProperty(0x4b, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetEnableManualPan(BOOL propVal)
{
	SetProperty(0x4b, VT_BOOL, propVal);
}

BOOL CCsdEft::GetEnableTopmost()
{
	BOOL result;
	GetProperty(0x4c, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetEnableTopmost(BOOL propVal)
{
	SetProperty(0x4c, VT_BOOL, propVal);
}

CString CCsdEft::GetDialogTitle()
{
	CString result;
	GetProperty(0x4d, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetDialogTitle(LPCTSTR propVal)
{
	SetProperty(0x4d, VT_BSTR, propVal);
}

BOOL CCsdEft::GetEnableCashoutDuplicate()
{
	BOOL result;
	GetProperty(0x4e, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetEnableCashoutDuplicate(BOOL propVal)
{
	SetProperty(0x4e, VT_BOOL, propVal);
}

CString CCsdEft::GetPinPadPort()
{
	CString result;
	GetProperty(0x4f, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPinPadPort(LPCTSTR propVal)
{
	SetProperty(0x4f, VT_BSTR, propVal);
}

CString CCsdEft::GetPinPadPortList()
{
	CString result;
	GetProperty(0x50, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPinPadPortList(LPCTSTR propVal)
{
	SetProperty(0x50, VT_BSTR, propVal);
}

long CCsdEft::GetCsdReservedProperty1()
{
	long result;
	GetProperty(0x51, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedProperty1(long propVal)
{
	SetProperty(0x51, VT_I4, propVal);
}

long CCsdEft::GetCsdReservedProperty2()
{
	long result;
	GetProperty(0x52, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedProperty2(long propVal)
{
	SetProperty(0x52, VT_I4, propVal);
}

long CCsdEft::GetCsdReservedProperty3()
{
	long result;
	GetProperty(0x53, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedProperty3(long propVal)
{
	SetProperty(0x53, VT_I4, propVal);
}

long CCsdEft::GetCsdReservedProperty4()
{
	long result;
	GetProperty(0x54, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedProperty4(long propVal)
{
	SetProperty(0x54, VT_I4, propVal);
}

long CCsdEft::GetSettleCardCount()
{
	long result;
	GetProperty(0x55, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetSettleCardCount(long propVal)
{
	SetProperty(0x55, VT_I4, propVal);
}

CString CCsdEft::GetCsdReservedString1()
{
	CString result;
	GetProperty(0x56, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedString1(LPCTSTR propVal)
{
	SetProperty(0x56, VT_BSTR, propVal);
}

CString CCsdEft::GetCsdReservedString2()
{
	CString result;
	GetProperty(0x57, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedString2(LPCTSTR propVal)
{
	SetProperty(0x57, VT_BSTR, propVal);
}

CString CCsdEft::GetTotalsData()
{
	CString result;
	GetProperty(0x58, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetTotalsData(LPCTSTR propVal)
{
	SetProperty(0x58, VT_BSTR, propVal);
}

CString CCsdEft::GetPhoneNumber()
{
	CString result;
	GetProperty(0x59, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPhoneNumber(LPCTSTR propVal)
{
	SetProperty(0x59, VT_BSTR, propVal);
}

CString CCsdEft::GetKvc()
{
	CString result;
	GetProperty(0x5a, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetKvc(LPCTSTR propVal)
{
	SetProperty(0x5a, VT_BSTR, propVal);
}

CString CCsdEft::GetPurchaseAnalysisData()
{
	CString result;
	GetProperty(0x5b, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPurchaseAnalysisData(LPCTSTR propVal)
{
	SetProperty(0x5b, VT_BSTR, propVal);
}

BOOL CCsdEft::GetCsdReservedBool1()
{
	BOOL result;
	GetProperty(0x5c, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedBool1(BOOL propVal)
{
	SetProperty(0x5c, VT_BOOL, propVal);
}

BOOL CCsdEft::GetCsdReservedBool2()
{
	BOOL result;
	GetProperty(0x5d, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedBool2(BOOL propVal)
{
	SetProperty(0x5d, VT_BOOL, propVal);
}

BOOL CCsdEft::GetCsdReservedBool3()
{
	BOOL result;
	GetProperty(0x5e, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedBool3(BOOL propVal)
{
	SetProperty(0x5e, VT_BOOL, propVal);
}

BOOL CCsdEft::GetCsdReservedBool4()
{
	BOOL result;
	GetProperty(0x5f, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedBool4(BOOL propVal)
{
	SetProperty(0x5f, VT_BOOL, propVal);
}

BOOL CCsdEft::GetCsdReservedBool5()
{
	BOOL result;
	GetProperty(0x60, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedBool5(BOOL propVal)
{
	SetProperty(0x60, VT_BOOL, propVal);
}

BOOL CCsdEft::GetResetTotals()
{
	BOOL result;
	GetProperty(0x61, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetResetTotals(BOOL propVal)
{
	SetProperty(0x61, VT_BOOL, propVal);
}

CString CCsdEft::GetSvrPhoneNumber()
{
	CString result;
	GetProperty(0x62, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetSvrPhoneNumber(LPCTSTR propVal)
{
	SetProperty(0x62, VT_BSTR, propVal);
}

CString CCsdEft::GetSvrPhonePrefix()
{
	CString result;
	GetProperty(0x63, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetSvrPhonePrefix(LPCTSTR propVal)
{
	SetProperty(0x63, VT_BSTR, propVal);
}

CString CCsdEft::GetSvrTcpipAddress()
{
	CString result;
	GetProperty(0x64, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetSvrTcpipAddress(LPCTSTR propVal)
{
	SetProperty(0x64, VT_BSTR, propVal);
}

CString CCsdEft::GetSvrTcpipPort()
{
	CString result;
	GetProperty(0x65, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetSvrTcpipPort(LPCTSTR propVal)
{
	SetProperty(0x65, VT_BSTR, propVal);
}

CString CCsdEft::GetPinPadComPort()
{
	CString result;
	GetProperty(0x66, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPinPadComPort(LPCTSTR propVal)
{
	SetProperty(0x66, VT_BSTR, propVal);
}

CString CCsdEft::GetPrinterName()
{
	CString result;
	GetProperty(0x67, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPrinterName(LPCTSTR propVal)
{
	SetProperty(0x67, VT_BSTR, propVal);
}

CString CCsdEft::GetJournalDirectory()
{
	CString result;
	GetProperty(0x68, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetJournalDirectory(LPCTSTR propVal)
{
	SetProperty(0x68, VT_BSTR, propVal);
}

CString CCsdEft::GetJournalFilename()
{
	CString result;
	GetProperty(0x69, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetJournalFilename(LPCTSTR propVal)
{
	SetProperty(0x69, VT_BSTR, propVal);
}

BOOL CCsdEft::GetCsdReservedBool6()
{
	BOOL result;
	GetProperty(0x6a, VT_BOOL, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedBool6(BOOL propVal)
{
	SetProperty(0x6a, VT_BOOL, propVal);
}

CString CCsdEft::GetCsdReservedString3()
{
	CString result;
	GetProperty(0x6b, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedString3(LPCTSTR propVal)
{
	SetProperty(0x6b, VT_BSTR, propVal);
}

CString CCsdEft::GetCsdReservedString4()
{
	CString result;
	GetProperty(0x6c, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedString4(LPCTSTR propVal)
{
	SetProperty(0x6c, VT_BSTR, propVal);
}

CString CCsdEft::GetCsdReservedString5()
{
	CString result;
	GetProperty(0x6d, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedString5(LPCTSTR propVal)
{
	SetProperty(0x6d, VT_BSTR, propVal);
}

long CCsdEft::GetTraceFileSizeLimit()
{
	long result;
	GetProperty(0x6e, VT_I4, (void*)&result);
	return result;
}

void CCsdEft::SetTraceFileSizeLimit(long propVal)
{
	SetProperty(0x6e, VT_I4, propVal);
}

CString CCsdEft::GetTraceFileName()
{
	CString result;
	GetProperty(0x6f, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetTraceFileName(LPCTSTR propVal)
{
	SetProperty(0x6f, VT_BSTR, propVal);
}

CString CCsdEft::GetPrintSystem()
{
	CString result;
	GetProperty(0x70, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetPrintSystem(LPCTSTR propVal)
{
	SetProperty(0x70, VT_BSTR, propVal);
}

CString CCsdEft::GetCsdReservedString6()
{
	CString result;
	GetProperty(0x71, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCsdReservedString6(LPCTSTR propVal)
{
	SetProperty(0x71, VT_BSTR, propVal);
}

CString CCsdEft::GetRrn()
{
	CString result;
	GetProperty(0x72, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetRrn(LPCTSTR propVal)
{
	SetProperty(0x72, VT_BSTR, propVal);
}

CString CCsdEft::GetAddress()
{
	CString result;
	GetProperty(0x73, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetAddress(LPCTSTR propVal)
{
	SetProperty(0x73, VT_BSTR, propVal);
}

CString CCsdEft::GetCardName()
{
	CString result;
	GetProperty(0x74, VT_BSTR, (void*)&result);
	return result;
}

void CCsdEft::SetCardName(LPCTSTR propVal)
{
	SetProperty(0x74, VT_BSTR, propVal);
}

CY CCsdEft::GetAmtCash()
{
	CY result;
	GetProperty(0x75, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetAmtCash(const CY& propVal)
{
	SetProperty(0x75, VT_CY, &propVal);
}

CY CCsdEft::GetAmtCreditLimit()
{
	CY result;
	GetProperty(0x76, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetAmtCreditLimit(const CY& propVal)
{
	SetProperty(0x76, VT_CY, &propVal);
}

CY CCsdEft::GetAmtTip()
{
	CY result;
	GetProperty(0x77, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetAmtTip(const CY& propVal)
{
	SetProperty(0x77, VT_CY, &propVal);
}

CY CCsdEft::GetAmtPurchase()
{
	CY result;
	GetProperty(0x78, VT_CY, (void*)&result);
	return result;
}

void CCsdEft::SetAmtPurchase(const CY& propVal)
{
	SetProperty(0x78, VT_CY, &propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCsdEft operations

void CCsdEft::DoReset()
{
	InvokeHelper(0x79, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoCardSwipe()
{
	InvokeHelper(0x7a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoChequeVerify()
{
	InvokeHelper(0x7b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoControlPanel()
{
	InvokeHelper(0x7c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoDisplayStatus()
{
	InvokeHelper(0x7d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoGetLastReceipt()
{
	InvokeHelper(0x7e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoGetLastTransaction()
{
	InvokeHelper(0x7f, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod1()
{
	InvokeHelper(0x80, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod2()
{
	InvokeHelper(0x81, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoInvokeApplet(LPCTSTR Applet)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x82, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Applet);
}

void CCsdEft::DoLogon()
{
	InvokeHelper(0x83, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoQueryCard()
{
	InvokeHelper(0x84, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoReprintReceipt()
{
	InvokeHelper(0x85, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod3()
{
	InvokeHelper(0x86, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod4()
{
	InvokeHelper(0x87, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSelfTest()
{
	InvokeHelper(0x88, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSettlementCutover()
{
	InvokeHelper(0x89, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSettlementEnquiry()
{
	InvokeHelper(0x8a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSettlementReconcile()
{
	InvokeHelper(0x8b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoStatus()
{
	InvokeHelper(0x8c, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoTransaction()
{
	InvokeHelper(0x8d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod5()
{
	InvokeHelper(0x8e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod6()
{
	InvokeHelper(0x8f, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSoftwareDownload()
{
	InvokeHelper(0x90, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSoftwareActivate()
{
	InvokeHelper(0x91, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoJournalViewer()
{
	InvokeHelper(0x92, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSetupPinPad()
{
	InvokeHelper(0x93, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoShowDialog(BOOL Show)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x94, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Show);
}

void CCsdEft::DoSettlement()
{
	InvokeHelper(0x95, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoDisplaySettlement()
{
	InvokeHelper(0x96, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod7()
{
	InvokeHelper(0x97, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod8()
{
	InvokeHelper(0x98, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::CsdReservedMethod9()
{
	InvokeHelper(0x9a, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoConfigMerchant()
{
	InvokeHelper(0x9b, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoSetFocus(BOOL EnableFocus)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0x9c, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 EnableFocus);
}

void CCsdEft::DoSetAutoLogonTime()
{
	InvokeHelper(0x9d, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoTestComms()
{
	InvokeHelper(0x9e, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::DoGetPending()
{
	InvokeHelper(0x9f, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CCsdEft::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
