#if !defined(AFX_CSDEFT_H__E471C7F8_731B_4243_864F_2E35175A57C1__INCLUDED_)
#define AFX_CSDEFT_H__E471C7F8_731B_4243_864F_2E35175A57C1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCsdEft wrapper class

class CCsdEft : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCsdEft)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xd548a364, 0x6579, 0x11d0, { 0x91, 0x3c, 0x44, 0x45, 0x53, 0x54, 0x0, 0x0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetResponseText();
	void SetResponseText(LPCTSTR);
	CString GetResponseCode();
	void SetResponseCode(LPCTSTR);
	CString GetTxnType();
	void SetTxnType(LPCTSTR);
	long GetStan();
	void SetStan(long);
	CString GetPanSource();
	void SetPanSource(LPCTSTR);
	CString GetPan();
	void SetPan(LPCTSTR);
	CString GetNii();
	void SetNii(LPCTSTR);
	long GetMerchant();
	void SetMerchant(long);
	CString GetTrack2();
	void SetTrack2(LPCTSTR);
	CString GetTrack1();
	void SetTrack1(LPCTSTR);
	long GetDialogX();
	void SetDialogX(long);
	long GetDialogY();
	void SetDialogY(long);
	CString GetDateSettlement();
	void SetDateSettlement(LPCTSTR);
	CString GetDialogType();
	void SetDialogType(LPCTSTR);
	CString GetAccountType();
	void SetAccountType(LPCTSTR);
	CString GetTxnRef();
	void SetTxnRef(LPCTSTR);
	CString GetPinPadVersion();
	void SetPinPadVersion(LPCTSTR);
	CString GetPinPadSerialNumber();
	void SetPinPadSerialNumber(LPCTSTR);
	CString GetDataField();
	void SetDataField(LPCTSTR);
	CString GetReceipt();
	void SetReceipt(LPCTSTR);
	long GetTimeout();
	void SetTimeout(long);
	BOOL GetConfigLocked();
	void SetConfigLocked(BOOL);
	BOOL GetCutReceipt();
	void SetCutReceipt(BOOL);
	BOOL GetLoggedOn();
	void SetLoggedOn(BOOL);
	CString GetDateExpiry();
	void SetDateExpiry(LPCTSTR);
	CY GetTotalPurchase();
	void SetTotalPurchase(const CY&);
	CY GetTotalCash();
	void SetTotalCash(const CY&);
	CY GetTotalRefund();
	void SetTotalRefund(const CY&);
	long GetTotalPurchaseCount();
	void SetTotalPurchaseCount(long);
	long GetTotalCashCount();
	void SetTotalCashCount(long);
	long GetTotalRefundCount();
	void SetTotalRefundCount(long);
	CString GetCaid();
	void SetCaid(LPCTSTR);
	CString GetCatid();
	void SetCatid(LPCTSTR);
	BOOL GetSuccess();
	void SetSuccess(BOOL);
	CString GetDate();
	void SetDate(LPCTSTR);
	CString GetTime();
	void SetTime(LPCTSTR);
	BOOL GetEnableTip();
	void SetEnableTip(BOOL);
	long GetResponseType();
	void SetResponseType(long);
	CString GetChqSerialNumber();
	void SetChqSerialNumber(LPCTSTR);
	CString GetChqBranch();
	void SetChqBranch(LPCTSTR);
	CString GetChqAccount();
	void SetChqAccount(LPCTSTR);
	CString GetDialogPosition();
	void SetDialogPosition(LPCTSTR);
	long GetMessageType();
	void SetMessageType(long);
	CString GetEftposNetwork();
	void SetEftposNetwork(LPCTSTR);
	BOOL GetPrintJournal();
	void SetPrintJournal(BOOL);
	CString GetPosVendor();
	void SetPosVendor(LPCTSTR);
	CString GetPosProductId();
	void SetPosProductId(LPCTSTR);
	CString GetPosVersion();
	void SetPosVersion(LPCTSTR);
	CString GetLicenseId();
	void SetLicenseId(LPCTSTR);
	CY GetSettleTotal();
	void SetSettleTotal(const CY&);
	CY GetSettleTotalDebit();
	void SetSettleTotalDebit(const CY&);
	CY GetSettleTotalCredit();
	void SetSettleTotalCredit(const CY&);
	BOOL GetReceiptAutoPrint();
	void SetReceiptAutoPrint(BOOL);
	CString GetCardType();
	void SetCardType(LPCTSTR);
	BOOL GetReady();
	void SetReady(BOOL);
	BOOL GetInstalled();
	void SetInstalled(BOOL);
	long GetVersionMajor();
	void SetVersionMajor(long);
	long GetVersionMinor();
	void SetVersionMinor(long);
	long GetVersionRevision();
	void SetVersionRevision(long);
	BOOL GetEnableErrorDialog();
	void SetEnableErrorDialog(BOOL);
	CString GetFilename();
	void SetFilename(LPCTSTR);
	CString GetAiic();
	void SetAiic(LPCTSTR);
	CY GetSettleTotalPurchase();
	void SetSettleTotalPurchase(const CY&);
	CY GetSettleTotalRefund();
	void SetSettleTotalRefund(const CY&);
	CString GetAuthCode();
	void SetAuthCode(LPCTSTR);
	BOOL GetLastTxnSuccess();
	void SetLastTxnSuccess(BOOL);
	CY GetSettleTotalCash();
	void SetSettleTotalCash(const CY&);
	CString GetSettleCardTotals();
	void SetSettleCardTotals(LPCTSTR);
	long GetSettleCountCash();
	void SetSettleCountCash(long);
	long GetSettleCount();
	void SetSettleCount(long);
	long GetSettleCountCredit();
	void SetSettleCountCredit(long);
	long GetSettleCountDebit();
	void SetSettleCountDebit(long);
	long GetSettleCountPurchase();
	void SetSettleCountPurchase(long);
	long GetSettleCountRefund();
	void SetSettleCountRefund(long);
	BOOL GetEnableManualPan();
	void SetEnableManualPan(BOOL);
	BOOL GetEnableTopmost();
	void SetEnableTopmost(BOOL);
	CString GetDialogTitle();
	void SetDialogTitle(LPCTSTR);
	BOOL GetEnableCashoutDuplicate();
	void SetEnableCashoutDuplicate(BOOL);
	CString GetPinPadPort();
	void SetPinPadPort(LPCTSTR);
	CString GetPinPadPortList();
	void SetPinPadPortList(LPCTSTR);
	long GetCsdReservedProperty1();
	void SetCsdReservedProperty1(long);
	long GetCsdReservedProperty2();
	void SetCsdReservedProperty2(long);
	long GetCsdReservedProperty3();
	void SetCsdReservedProperty3(long);
	long GetCsdReservedProperty4();
	void SetCsdReservedProperty4(long);
	long GetSettleCardCount();
	void SetSettleCardCount(long);
	CString GetCsdReservedString1();
	void SetCsdReservedString1(LPCTSTR);
	CString GetCsdReservedString2();
	void SetCsdReservedString2(LPCTSTR);
	CString GetTotalsData();
	void SetTotalsData(LPCTSTR);
	CString GetPhoneNumber();
	void SetPhoneNumber(LPCTSTR);
	CString GetKvc();
	void SetKvc(LPCTSTR);
	CString GetPurchaseAnalysisData();
	void SetPurchaseAnalysisData(LPCTSTR);
	BOOL GetCsdReservedBool1();
	void SetCsdReservedBool1(BOOL);
	BOOL GetCsdReservedBool2();
	void SetCsdReservedBool2(BOOL);
	BOOL GetCsdReservedBool3();
	void SetCsdReservedBool3(BOOL);
	BOOL GetCsdReservedBool4();
	void SetCsdReservedBool4(BOOL);
	BOOL GetCsdReservedBool5();
	void SetCsdReservedBool5(BOOL);
	BOOL GetResetTotals();
	void SetResetTotals(BOOL);
	CString GetSvrPhoneNumber();
	void SetSvrPhoneNumber(LPCTSTR);
	CString GetSvrPhonePrefix();
	void SetSvrPhonePrefix(LPCTSTR);
	CString GetSvrTcpipAddress();
	void SetSvrTcpipAddress(LPCTSTR);
	CString GetSvrTcpipPort();
	void SetSvrTcpipPort(LPCTSTR);
	CString GetPinPadComPort();
	void SetPinPadComPort(LPCTSTR);
	CString GetPrinterName();
	void SetPrinterName(LPCTSTR);
	CString GetJournalDirectory();
	void SetJournalDirectory(LPCTSTR);
	CString GetJournalFilename();
	void SetJournalFilename(LPCTSTR);
	BOOL GetCsdReservedBool6();
	void SetCsdReservedBool6(BOOL);
	CString GetCsdReservedString3();
	void SetCsdReservedString3(LPCTSTR);
	CString GetCsdReservedString4();
	void SetCsdReservedString4(LPCTSTR);
	CString GetCsdReservedString5();
	void SetCsdReservedString5(LPCTSTR);
	long GetTraceFileSizeLimit();
	void SetTraceFileSizeLimit(long);
	CString GetTraceFileName();
	void SetTraceFileName(LPCTSTR);
	CString GetPrintSystem();
	void SetPrintSystem(LPCTSTR);
	CString GetCsdReservedString6();
	void SetCsdReservedString6(LPCTSTR);
	CString GetRrn();
	void SetRrn(LPCTSTR);
	CString GetAddress();
	void SetAddress(LPCTSTR);
	CString GetCardName();
	void SetCardName(LPCTSTR);
	CY GetAmtCash();
	void SetAmtCash(const CY&);
	CY GetAmtCreditLimit();
	void SetAmtCreditLimit(const CY&);
	CY GetAmtTip();
	void SetAmtTip(const CY&);
	CY GetAmtPurchase();
	void SetAmtPurchase(const CY&);

// Operations
public:
	void DoReset();
	void DoCardSwipe();
	void DoChequeVerify();
	void DoControlPanel();
	void DoDisplayStatus();
	void DoGetLastReceipt();
	void DoGetLastTransaction();
	void CsdReservedMethod1();
	void CsdReservedMethod2();
	void DoInvokeApplet(LPCTSTR Applet);
	void DoLogon();
	void DoQueryCard();
	void DoReprintReceipt();
	void CsdReservedMethod3();
	void CsdReservedMethod4();
	void DoSelfTest();
	void DoSettlementCutover();
	void DoSettlementEnquiry();
	void DoSettlementReconcile();
	void DoStatus();
	void DoTransaction();
	void CsdReservedMethod5();
	void CsdReservedMethod6();
	void DoSoftwareDownload();
	void DoSoftwareActivate();
	void DoJournalViewer();
	void DoSetupPinPad();
	void DoShowDialog(BOOL Show);
	void DoSettlement();
	void DoDisplaySettlement();
	void CsdReservedMethod7();
	void CsdReservedMethod8();
	void CsdReservedMethod9();
	void DoConfigMerchant();
	void DoSetFocus(BOOL EnableFocus);
	void DoSetAutoLogonTime();
	void DoTestComms();
	void DoGetPending();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CSDEFT_H__E471C7F8_731B_4243_864F_2E35175A57C1__INCLUDED_)
