//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by POSClient.rc
//
#define VS_VERSION_INFO1                2
#define IDCANCEL2                       3
#define IDC_CLOCKOUT                    3
#define IDC_CLOCKIN                     4
#define IDC_BUTTON_CANCLEORDER          101
#define IDC_BUTTON_ARRIVE               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_LOGINDLG                    104
#define IDS_CLOCKHINT                   104
#define IDS_CLOCKIN                     105
#define IDD_MAINSHEET                   106
#define IDS_NOUSER                      106
#define IDS_WRONGPSW                    107
#define IDS_NOPRIVALAGE                 108
#define IDS_READY                       109
#define IDS_NOACTION                    110
#define IDS_NUMERROR                    111
#define IDS_INPUTLOGIN                  112
#define IDS_INPUTTBL                    113
#define IDS_TBLNOERROR                  114
#define IDS_TBLINOPERATE                115
#define IDS_NOTFINDTBL                  116
#define IDS_INPUTGUEST                  117
#define IDS_TOMANYG                     118
#define IDS_ALREADYOPEN                 119
#define IDS_INPUTSERIAL                 120
#define IDS_USEPOINT                    120
#define IDS_NOTFIND                     121
#define IDS_SUBTOTAL                    122
#define IDS_SERVICE                     123
#define IDS_PAYED                       124
#define IDS_SELECTSERVICE               125
#define IDS_SELECTDISCOUNT              126
#define IDS_TBLNAME                     127
#define IDR_MAINFRAME                   128
#define IDS_CHKNAME                     128
#define IDD_ORDER                       129
#define IDS_CHKNUM                      129
#define IDS_GUESTNUM                    130
#define IDS_SEARCHHINT                  131
#define IDS_NOTALLOWCOND                132
#define IDS_INPUTPRICE                  133
#define IDS_INPUTWEIGHT                 134
#define IDS_TOOMUCH                     135
#define IDD_FLOOR                       136
#define IDS_CONFIRM                     136
#define IDI_ICON_FOOD                   137
#define IDS_VOID                        137
#define IDD_PAY                         138
#define IDS_VOIDTIME                    138
#define IDD_DIALOG1                     139
#define IDD_NUMINPUT                    139
#define IDS_REQUESTAUTH                 139
#define IDS_SEND                        140
#define IDD_TABLESTATUS                 141
#define IDS_SENDTIME                    141
#define IDD_VOIDREASON                  142
#define IDS_INPUTQUANTITY               142
#define IDD_SPLIT                       143
#define IDS_CANNOTMODIFY                143
#define IDD_CHECK                       144
#define IDS_TOOMANYCHK                  144
#define IDD_PICKUP                      145
#define IDS_ALREADYSEND                 145
#define IDD_DISCOUNT                    146
#define IDS_INPUTITEMNAME               146
#define IDD_PAY1                        147
#define IDD_FUNCTION                    147
#define IDS_CANNOTEMPTY                 147
#define IDD_MODIFY                      148
#define IDS_REFUNDHINT                  148
#define IDS_INPUTCARDNUM                149
#define IDD_DIALOG2                     150
#define IDD_INFOMATION                  150
#define IDS_INSUFFICENT                 150
#define IDS_DEMOBTN                     150
#define IDD_DIALOG3                     151
#define IDD_STRINGINPUT                 151
#define IDS_NOCARD                      151
#define IDD_DIALOG4                     152
#define IDD_MANAGER                     152
#define IDS_CARDBALANCE                 152
#define IDD_DIALOG5                     153
#define IDD_SELECTITEM                  153
#define IDS_INPUTAMOUNT                 153
#define IDB_BITMAP1                     154
#define IDS_AMOUNTHINT                  154
#define IDB_BITMAP2                     155
#define IDS_INPUTCOMMENT                155
#define IDD_PREORDER                    156
#define IDS_CHANGE                      156
#define IDD_MSGBOX                      157
#define IDS_OPENTIME                    157
#define IDS_SERIAL                      158
#define IDS_EMPLOYEE                    159
#define IDS_POINTCONSUME                159
#define IDS_TOTAL                       160
#define IDS_PRINTTIMES                  161
#define IDS_REFUNDTOTAL                 162
#define IDS_INPUTCHKNAME                163
#define IDD_REPORT                      164
#define IDS_MODIFY                      164
#define IDS_INPUTTOTBL                  165
#define IDS_WRONGTBL                    166
#define IDS_INUSING                     167
#define IDS_VOIDREASON                  168
#define IDS_EMPSERVICE                  169
#define IDS_TIMEGO                      170
#define IDS_AMOUNTDUE                   171
#define IDS_SELECTSPLIT                 172
#define IDS_CANOTSPLIT                  173
#define IDS_SPLITCOUNT                  174
#define IDS_ALREADYSPLIT                175
#define IDS_PRINTTIME                   176
#define IDS_SALEDISHES                  177
#define IDS_DISCOUNT                    178
#define IDS_REFUND                      179
#define IDS_ACTUALM                     180
#define IDS_OK                          181
#define IDS_CANCEL                      182
#define IDS_STATUS                      183
#define IDS_PREPAGE                     184
#define IDS_NEXTPAGE                    185
#define IDS_TIMESPAN                    186
#define IDS_REFRESH                     187
#define IDS_PRINT                       188
#define IDS_EXIT                        189
#define IDS_INPUTPERCENT                190
#define IDD_CUSTOMER                    190
#define IDS_EMPMEAL                     191
#define IDD_NOTIFYKIT                   191
#define IDS_NETSALE                     192
#define IDS_TTLSALE                     193
#define IDD_ALTER                       193
#define IDD_CUSTSEARCH                  194
#define IDS_SELECTCHK                   194
#define IDS_STRING194                   194
#define IDS_PREPRINT                    194
#define IDD_SOLDOUT                     195
#define IDS_ALREADYRUN                  195
#define IDD_SOLDITEM                    196
#define IDS_INICFG                      196
#define IDS_CONECTDB                    197
#define IDD_REMIND                      198
#define IDS_CHECKREG                    198
#define IDS_INITPRINT                   199
#define IDD_VIEWCHK                     200
#define IDB_BITMAP4                     200
#define IDS_LOADDISPLAY                 200
#define IDS_DEBT                        201
#define IDD_EDITPRICE                   201
#define IDS_TAKEAWAY                    202
#define IDD_EDITPRICEITEM               202
#define IDS_SELECTRECORD                203
#define IDI_ICONNUM                     203
#define IDS_DATABASENOIP                204
#define IDS_TRAINMODE                   205
#define IDS_CONFIRM_CLEANSOLD           206
#define IDS_INPUTVIPCARD                207
#define IDD_FLOORCHOOSE                 207
#define IDS_INPUTVIPNAME                208
#define IDD_OPENTABLE                   208
#define IDS_CARDALREADYEXIST            209
#define IDD_PROGRESS                    209
#define IDS_CREATEVIPOK                 210
#define IDD_PICKCHK                     210
#define IDS_CLEAR                       211
#define IDD_DIALOG6                     211
#define IDS_SOFTKEY                     212
#define IDS_SELECTVIP                   213
#define IDI_ICON_STOP                   213
#define IDS_CARDNO                      214
#define IDS_NAME                        215
#define IDS_AMOUNT                      216
#define IDR_VERSION2                    216
#define IDS_PHONE                       217
#define IDS_RECHARGE                    218
#define IDS_AMOUNTEXCEED                219
#define IDS_GOTOCHK                     219
#define IDS_PRICE                       220
#define IDS_BOOKED                      221
#define IDS_TRANSINFO                   222
#define IDS_ALL                         223
#define IDS_COMBINEFAIL1                224
#define IDS_COMBINEFAIL                 225
#define IDS_SENDFROM                    226
#define IDS_CHOOSEITEMCOPY              227
#define IDS_CONFIRMSHIFT                228
#define IDS_SHIFTINFO                   229
#define IDS_CONFIRMEOD                  230
#define IDS_HASUNPAYCHK                 231
#define IDS_EOFSUCCESS                  232
#define IDS_SAILREPORT                  233
#define IDS_CHECKNUMS                   234
#define IDS_GSTNUMS                     235
#define IDS_SALEPCHK                    236
#define IDS_SALEPGST                    237
#define IDS_REOPENCHK                   238
#define IDS_RPTOVERVIEW                 239
#define IDS_RPTDEPART                   240
#define IDS_PAMENTOV                    241
#define IDS_RPTRETURN                   242
#define IDS_RETURNAMOUNT                243
#define IDS_RETURNNUMS                  244
#define IDS_RPTREFUND                   245
#define IDS_REFUNDAMOUNT                246
#define IDS_REFUNDNUMS                  247
#define IDS_UNPAYAMOUNT                 248
#define IDS_UNPAYNUMS                   249
#define IDS_RPTDISHT                    250
#define IDS_SOLDOUTCTN                  251
#define IDS_SELECTITEM                  252
#define IDS_REMINDSEND                  253
#define IDS_REMINDOK                    254
#define IDS_ADDREQUEST                  255
#define IDS_INPUTPARTY                  256
#define IDS_PARTY                       257
#define IDS_CANCELORDER                 258
#define IDS_PREORDERCUS                 259
#define IDS_ARRIVETIME                  260
#define IDS_HOUR                        261
#define IDS_MINUTE                      262
#define IDS_NOPREPRINT                  263
#define IDS_SUBCHK                      264
#define IDS_CLOSETIME                   265
#define IDS_EMPLOYE                     266
#define IDS_INPUTSERAL                  267
#define IDS_SALEABLE                    268
#define IDS_MANUALSOLD                  269
#define IDS_NUMSOLD                     270
#define IDS_TODAYSOLD                   271
#define IDS_EMPTYINPUT                  272
#define IDS_EXPIER                      273
#define IDS_NOTVALID                    274
#define IDS_GUOQI                       275
#define IDS_NOTTHISMACH                 276
#define IDS_NOTREG                      277
#define IDS_REGINFO                     278
#define IDS_ADDRESERVE                  278
#define IDS_INVOICE                     279
#define IDS_COMBINE                     280
#define IDS_FREE                        281
#define IDS_DISH                        282
#define IDS_TBLNOTOPEN                  283
#define IDS_SHIFTTOTAL                  284
#define IDS_RPTPERIOD                   285
#define IDS_FORCELOCK                   286
#define IDS_CONDIMENT                   287
#define IDS_ORDERED                     288
#define IDS_TAX                         289
#define IDS_CHKNAME2                    290
#define IDS_INPUTCHKNAME2               291
#define IDS_INPUTSEATNUM                292
#define IDS_INPUTVOIDNUM                293
#define IDD_WEBDLG                      294
#define IDS_CONFIRMSHUT                 294
#define IDR_HTML_WEBDLG                 295
#define IDD_TIMECOUNT                   295
#define IDS_POSCSYS                     295
#define IDD_ABOUT                       296
#define IDS_CONFIGSYS                   296
#define IDS_REPORTSYS                   297
#define IDD_CHANGEPSW                   297
#define IDS_PARTYSYS                    298
#define IDD_COMBOMEAL                   298
#define IDS_RECHARGESEND                299
#define IDD_SHIFT                       299
#define IDS_PRE_PENDING                 299
#define IDS_SESSION                     300
#define IDS_TOTALTBL                    301
#define IDS_PRE_CONFIRM                 301
#define IDS_TOTALGST                    302
#define IDS_PRE_DELETE                  302
#define IDS_TOTALUSED                   303
#define IDS_PRE_ARRIVE                  303
#define IDS_REGWARN                     304
#define IDS_IGNORE                      304
#define IDS_PARTYCHOOSE                 305
#define IDS_LINKTABLE                   306
#define IDS_SAVEEODDATA                 307
#define IDS_SENDMESSAGE                 308
#define IDS_SEPARATECFM                 308
#define IDS_DELCONFIRM                  308
#define IDS_SENDDEPOS                   309
#define IDS_DODAYEND                    310
#define IDS_DOBACKUP                    311
#define IDS_BACKUPTO                    312
#define IDS_COMBINEPAY                  313
#define IDS_CANCELTRANS                 314
#define IDS_CANTPICK                    315
#define IDS_COMBINESEND                 316
#define IDS_SWAPCOURSE                  317
#define IDS_PROCESS                     317
#define IDS_NOPAYMENT                   318
#define IDS_CONSUMELIMIT                319
#define IDS_MINIADJUST                  320
#define IDS_NOPREPRINTER                321
#define IDS_TAKEOUT                     322
#define IDS_ITEMID                      323
#define IDS_ITEMNAME                    324
#define IDS_UNIT                        325
#define IDS_NUM                         326
#define IDS_PICKUPPARTY                 327
#define IDS_COUPON                      328
#define IDS_CURDAY                      329
#define IDS_YESTERDAY                   330
#define IDS_CURMONTH                    331
#define IDS_LASTMONTH                   332
#define IDS_ALLDEPART                   333
#define IDS_HOWTOMAKE                   334
#define IDS_INVOCENUM                   335
#define IDS_CHOOSETABLE                 336
#define IDS_MAJORSALES                  337
#define IDS_DIREXIST                    338
#define IDS_SOLDOUTNUM                  339
#define IDS_COMBINEFAIL2                340
#define IDS_ORIGNALINVOICE              341
#define IDS_WAITMK                      342
#define IDS_MAKENOW                     343
#define IDS_VOID2                       344
#define IDS_BACK                        345
#define IDS_MESSAGEHEAD                 346
#define IDS_CONFIRMQUIT                 347
#define IDS_STRING348                   348
#define IDS_BALANCE                     348
#define IDS_REMARK                      349
#define IDS_SENCONDCLOSE                350
#define IDS_CLEARSOLDOUT                351
#define IDS_ITEMSLU                     352
#define IDS_SOLDDETAIL                  353
#define IDS_ITEMDETAIL                  354
#define IDS_WITH                        355
#define IDS_WITHOUT                     356
#define IDS_MORE                        357
#define IDS_LESS                        358
#define IDS_HANDINPUT                   359
#define IDS_WAITCHK                     360
#define IDS_MAKECHK                     361
#define IDS_REMINDCHK                   362
#define IDS_REMINDSEL                   363
#define IDS_REMINDISHT                  364
#define IDS_SOLDSETTING                 365
#define IDS_LIMITAVAL                   366
#define IDS_LIMITTYPE                   367
#define IDS_RECOVERAFTER                368
#define IDS_EDIT                        369
#define IDS_ITEMPRICE                   370
#define IDS_NEWVIP                      371
#define IDS_FMNAME                      372
#define IDS_CANDEBET                    373
#define IDS_VIPINFO                     374
#define IDS_PRINTCHARGE                 375
#define IDS_CONSUME                     376
#define IDS_SCORE                       377
#define IDS_CARDPAY                     378
#define IDS_WAITTHINT                   379
#define IDS_REMINDHEAD                  380
#define IDS_REQUESTMAKE                 381
#define IDS_MAKEHEAD                    382
#define IDS_MAKETBL                     383
#define IDS_CHANGEPSW                   384
#define IDS_CURRENTPSW                  385
#define IDS_NEWPSW                      386
#define IDS_REPEATPSW                   387
#define IDS_NOTSAMEPSW                  388
#define IDS_WRONGPSW2                   389
#define IDS_SWAPCOURSE2                 390
#define IDS_ADDREQHINT                  391
#define IDS_COMBOMEALNUM                392
#define IDS_CHOOSECOMBOME               393
#define IDS_COMPLETE                    394
#define IDS_COMMEALGPOK                 395
#define IDS_COMMEALHINT                 396
#define IDS_NOTDISCOUNT                 397
#define IDB_BITMAP_STARTTIP             397
#define IDD_FLOORVIEW                   397
#define IDS_VIPRECHARGE                 398
#define IDB_BITMAP_CLOSE                398
#define IDS_CHOOSECOURSE                399
#define IDS_INPUTCASHIN                 400
#define IDS_INPUTCASHOUT                401
#define IDD_SENCONDSCREEN               401
#define IDD_SNDSCREEN                   401
#define IDS_CASHIN                      402
#define IDS_CASHOUT                     403
#define IDS_LASTSHIFT                   404
#define IDI_ICON_MAKE                   404
#define IDD_CUSTSEARCH2                 404
#define IDC                             404
#define IDS_WEBVIPRECHARGE              405
#define IDS_VIPNOTREG                   405
#define IDD_CUSTNEW2                    405
#define IDS_BUYNOW                      406
#define IDS_INVENOTREG                  407
#define IDS_TIPWELCOME                  408
#define IDS_TIPCHECK                    409
#define IDS_TIPGUEST                    410
#define IDS_TIPDAYS                     411
#define IDS_TABLEREMARK                 412
#define IDS_NETWARNING                  413
#define IDS_REGNOW                      414
#define IDS_REGLATER                    415
#define IDS_TABLEGST                    416
#define IDS_DISHMAKED                   417
#define IDS_DISHMAKED2                  418
#define IDS_INPUTCHKNUM                 419
#define IDS_NOTREG2                     420
#define IDS_REPORTNOTREG                421
#define IDS_CANCELMAKE                  422
#define IDS_SELECTDEPART                423
#define IDS_ADRESS                      424
#define IDS_ADDCUS                      425
#define IDS_ADDCUSINFO                  426
#define IDS_CANCELFREE                  427
#define IDS_PRINTTWICE                  428
#define IDS_GUESTNUM2                   429
#define IDS_IDS_CLEARALL                430
#define IDS_PRINT_ORDER                 431
#define IDS_VOIDMODE                    432
#define IDS_LOCATION                    433
#define IDS_IFPRINTCHK                  434
#define IDS_CLOCKOUT                    435
#define IDS_PICKCHKQ                    436
#define IDD_LANGUAGE                    436
#define IDS_INPUTPRICETOTAL             437
#define IDD_CLOCK                       437
#define IDS_SENDORDERHINT               438
#define IDS_MAKEITEM                    439
#define IDS_MAKEITEM2                   440
#define IDS_MEMBERCANCEL                441
#define IDS_MOLIN                       442
#define IDS_CONSUMLIMIT_TBL             443
#define IDD_EFTMSG                      444
#define IDS_CONSUMLIMIT_GST             444
#define IDS_QTOTAL                      445
#define IDD_WEIXINPAY                   445
#define IDS_QFREE                       446
#define IDB_BITMAP5                     446
#define IDB_BITMAP_WECHAT               446
#define IDD_VIEWWEBCHK                  446
#define IDS_NOTFINDITEM                 447
#define IDI_ICON1                       447
#define IDI_ICON_WECHAT                 447
#define IDD_WEIXINPAY1                  447
#define IDD_ALIPAY                      447
#define IDS_READCARD                    448
#define IDB_BITMAP_ALIPAY               448
#define IDD_RESERVEADD                  448
#define IDS_REOPEN                      449
#define IDB_BITMAP3                     449
#define IDB_WEXIN_HINT                  449
#define IDD_RESERVE                     449
#define IDS_LEVEL                       450
#define IDD_TIPSADD                     450
#define IDI_ICON_NEW                    450
#define IDS_PASSWORD                    451
#define IDD_DISPLAYSET                  451
#define IDS_PRINTSERVERNOTRUN           452
#define IDD_CHANGEPSW1                  452
#define IDD_ADDPOS                      452
#define IDS_PRINT_ERROR_OPENFAIL        453
#define IDD_ADDPOS1                     453
#define IDD_WEBLOGIN                    453
#define IDS_PRINT_ERROR_NETFAIL         454
#define IDS_PRINT_ERROR_COVEOPEN        455
#define IDS_PRINT_ERROR_PAPEROUT        456
#define IDS_PRINT_ERROR_ERRO            457
#define IDS_PRINT_ERROR_OTHER           458
#define IDS_DATABASE_LOWER              459
#define IDS_PAYED2                      460
#define IDS_UNPAYED                     461
#define IDS_CLOUDHINT                   462
#define IDS_SWITCHOK                    463
#define IDS_SYNCOK                      464
#define IDS_SWITCHFAIL                  465
#define IDS_TIPS                        466
#define IDS_NOTALLOWTBL                 467
#define IDS_PRINT_SERIAL                468
#define IDS_SKIP                        469
#define IDS_NEED_ACTIVE                 470
#define IDS_REGMAX                      471
#define IDS_DOWNLOAD                    472
#define IDS_SYNCOK2                     473
#define IDC_EDIT1                       1000
#define IDC_LIST1                       1001
#define IDC_EDIT8                       1001
#define IDC_LIST2                       1002
#define IDC_LIST3                       1003
#define IDC_EDIT2                       1004
#define IDC_LIST4                       1005
#define IDC_EDIT3                       1006
#define IDC_EDIT4                       1007
#define IDC_STATIC_BACK                 1007
#define IDC_STATIC_TIME                 1008
#define IDC_EDIT6                       1008
#define IDC_STATIC_LOG                  1009
#define IDC_EDIT7                       1009
#define IDC_STATIC_CHECK                1010
#define IDC_STATIC_TABLE                1011
#define IDC_STATIC_GUEST                1012
#define IDC_EDIT5                       1017
#define IDC_EDIT_DATE                   1017
#define IDC_BUTTON_PREPAGE              1018
#define IDC_STATIC_DISCOUNT             1019
#define IDC_BUTTON_IGNORE               1029
#define IDC_EDIT_ORDERID                1030
#define IDC_EDIT_GUESTNUM               1031
#define IDC_EDIT_TABLEID                1032
#define IDC_EDIT_TIME                   1033
#define IDC_EDIT_GUESTNAME              1034
#define IDC_EDIT_PHONE                  1035
#define IDC_BUTTON_NUM                  1036
#define IDC_EDIT_STATE                  1036
#define IDC_EDIT_LEVEL                  1037
#define IDC_BUTTON_PRINT_SERIAL         1037
#define IDC_STATIC1                     1038
#define IDC_STATIC6                     1039
#define IDC_REFRESH                     1042
#define IDC_BTPRINT                     1043
#define IDC_DATETIMEPICKER1             1044
#define IDC_DATETIMEPICKER2             1045
#define IDC_EDIT_CRADID                 1046
#define IDC_EDIT_NAME                   1047
#define IDC_RADIO2                      1049
#define IDC_STATIC_1                    1050
#define IDC_EDIT_AMOUNT                 1051
#define IDC_EDIT_SCORE                  1052
#define IDC_EDIT_PAY                    1053
#define IDC_EDIT_PASSWORD               1054
#define IDC_EDIT_SEX                    1055
#define IDC_EDIT_POINT                  1055
#define IDC_STATIC_2                    1056
#define IDC_CHECK1                      1057
#define IDC_COMBO1                      1058
#define IDC_BUTTON_SOFTKEY              1060
#define IDC_STATIC2                     1062
#define IDC_STATIC7                     1063
#define IDC_CANCEL_SOLD                 1064
#define IDC_BUTTON_EDIT                 1067
#define IDC_EDIT_ID                     1068
#define IDC_EDITP1                      1069
#define IDC_EDITP2                      1070
#define IDC_BUTTON_CLEAN                1070
#define IDC_EDITP3                      1071
#define IDC_RADIO1                      1071
#define IDC_EDITP4                      1072
#define IDC_CURDAY                      1072
#define IDC_EDITP5                      1073
#define IDC_LASTDAY                     1073
#define IDC_EDITU1                      1074
#define IDC_LASTMONTH                   1074
#define IDC_PROGRESS1                   1074
#define IDC_EDITU2                      1075
#define IDC_CURMONTH                    1075
#define IDC_EDITU3                      1076
#define IDC_EDITU4                      1077
#define IDC_STATIC_HINT                 1077
#define IDC_EDITU5                      1078
#define IDC_STATIC_URL                  1078
#define IDC_STATIC_NUM                  1078
#define IDC_STATIC3                     1080
#define IDC_STATIC4                     1081
#define IDC_STATIC5                     1082
#define IDC_STATICU1                    1083
#define IDC_STATIC8                     1083
#define IDC_STATICU2                    1084
#define IDC_STATIC9                     1084
#define IDC_STATICU3                    1085
#define IDC_STATICU4                    1086
#define IDC_STATICU5                    1087
#define IDC_STATICP1                    1088
#define IDC_STATICP2                    1089
#define IDC_STATICP3                    1090
#define IDC_STATICP4                    1091
#define IDC_STATICP5                    1092
#define IDC_STATIC_PIC                  1093
#define IDC_STATIC_AMOUNT               1094
#define IDC_STATIC_PAYED                1095
#define IDC_BUTTON_LOCATION             1096
#define IDC_STATIC_VER                  1098
#define IDC_CSDEFT                      1099
#define IDC_CSDEFTCTRL1                 1101
#define IDC_BUTTON_REOPEN               1102
#define IDC_LOGO                        1103
#define IDC_STATIC_POINT                1104
#define IDC_STATIC_TITLE                1105
#define IDC_STATIC_ARRIVE               1107
#define IDC_STATIC_NAME                 1108
#define IDC_STATIC_PHONE                1109
#define IDC_STATIC_GST                  1110
#define IDC_STATIC_TABLE1               1111
#define IDC_STATIC_REMARK               1112
#define IDC_STATIC_LOGO                 1113
#define IDC_CHECK2                      1115
#define IDC_SPIN1                       1116
#define IDC_SPIN2                       1117
#define IDC_SPIN3                       1118
#define IDC_CHECK3                      1119
#define IDC_DYNAMIC_CTRL                2000
#define IDC_TABLE0                      2000
#define IDC_BUTTON0                     3000
#define IDC_BUTTON1                     3001
#define IDC_BUTTON2                     3002
#define IDC_BUTTON3                     3003
#define IDC_BUTTON4                     3004
#define IDC_BUTTON5                     3005
#define IDC_BUTTON6                     3006
#define IDC_BUTTON7                     3007
#define IDC_BUTTON8                     3008
#define IDC_BUTTON9                     3009
#define IDC_BUTTON_OK                   3010
#define IDC_BUTTON_CLEAR                3011
#define IDC_BUTTON_CONDIMENT            3012
#define IDC_BUTTON_CLEARPRE             3012
#define IDC_BUTTON_READ                 3012
#define IDC_BUTTON_FUNCTION             3013
#define IDC_BUTTON00                    3014
#define IDC_BUTTON_DOT                  3015
#define IDC_BUTTON_CLOCK                3016
#define IDC_BUTTON_DEL                  3016
#define IDC_BUTTON_SIGN                 3017
#define IDC_BUTTON_CHANGE               3018
#define IDC_BUTTON_HELP                 3019
#define IDC_BUTTON_VIEW                 3020
#define IDC_BUTTON_SAVE                 3021
#define IDC_BUTTON_UP                   3023
#define IDC_BUTTON_DOWN                 3024
#define IDC_BUTTON_PAY                  3025
#define IDC_BUTTON_PRE                  3026
#define IDC_BUTTON_STATUS               3027
#define IDC_BUTTON_GOTO                 3027
#define IDC_BUTTON_CANCEL               3028
#define IDC_BUTTON_BEGIN                3029
#define IDC_BUTTON_NUMBER               3030
#define IDC_BUTTON_CASH                 3031
#define IDC_BUTTON_ADD                  3032
#define IDC_BUTTON_TRANSFER             3033
#define IDC_BUTTON_REPEAT               3034
#define IDC_BUTTON_VOID                 3035
#define IDC_BUTTON_LEFT                 3036
#define IDC_BUTTON_RIGHT                3037
#define IDC_BUTTON_SHARE                3038
#define IDC_BUTTON_COMBINE              3039
#define IDC_BUTTON_SPLITITEM            3040
#define IDC_BUTTON_GUEST                3041
#define IDC_BUTTON_DISCOUNT             3042
#define IDC_BUTTON_SERVICE              3043
#define IDC_BUTTON_PICKTAB              3044
#define IDC_BUTTON_PICKCHK              3045
#define IDC_BUTTON_SEND                 3046
#define IDC_BUTTON_PRINT                3047
#define IDC_BUTTON_SPLIT                3048
#define IDC_BUTTON_TIPS                 3048
#define IDC_BUTTON_ADDCHK               3049
#define IDC_BUTTON_CHKNAME              3050
#define IDC_BUTTON_REPORT               3051
#define IDC_BUTTON_MODIFY               3052
#define IDC_BUTTON_EDITCHK              3053
#define IDC_BUTTON_INCREASE             3054
#define IDC_BUTTON_DECREASE             3055
#define IDC_BUTTON_TAKEOUT              3056
#define IDC_BUTTON_REFUND               3057
#define IDC_BUTTON_MINIMIZE             3058
#define IDC_BUTTON_OPEN                 3059
#define IDC_BUTTON_SELECTALL            3060
#define IDC_BUTTON_REPORT1              3061
#define IDC_BUTTON_REPORT2              3062
#define IDC_BUTTON_REPORT3              3063
#define IDC_BUTTON_OPENITEM             3064
#define IDC_BUTTON_SHIFT                3065
#define IDC_BUTTON_SEARCH               3066
#define IDC_BUTTON_CTRLSHIFT            3067
#define IDC_BUTTON_REPRICE              3068
#define IDC_BUTTON_RECHARGE             3069
#define IDC_BUTTON_REMINDDISH           3070
#define IDC_BUTTON_NOTIFYKIT            3071
#define IDC_BUTTON_ALTERITEM            3072
#define IDC_BUTTON_FREEDISH             3073
#define IDC_BUTTON_REPORT4              3074
#define IDC_BUTTON_PRINTROUND           3075
#define IDC_BUTTON_COPYCHK              3076
#define IDC_BUTTON_ADDREQUEST           3077
#define IDC_BUTTON_SOLDOUT              3078
#define IDC_BUTTON_NEWCUSTOMER          3079
#define IDC_BUTTON_SWAPCOURSE           3080
#define IDC_BUTTON_CUSNAME              3081
#define IDC_BUTTON_PARTY                3082
#define IDC_BUTTON_DAYEND               3083
#define IDC_BUTTON_ABORTPAY             3084
#define IDC_BUTTON_EDITPRICE            3085
#define IDC_BUTTON_INVOICE              3086
#define IDC_BUTTON_TRANSITEM            3087
#define IDC_BUTTON_HANDINPUT            3088
#define IDC_BUTTON_LOGOUT               3089
#define IDC_BUTTON_DELETEALL            3090
#define IDC_BUTTON_PENDING              3091
#define IDC_BUTTON_TACHK                3092
#define IDC_BUTTON10                    3093
#define IDC_BUTTON_PREPRINT             3093
#define IDC_BUTTON20                    3094
#define IDC_BUTTON50                    3095
#define IDC_BUTTON100                   3096
#define IDC_BUTTON_MANAGEFUN            3097
#define IDC_BUTTON_SEATNUM              3098
#define IDC_BUTTON_WEBRECHARGE          3099
#define IDC_ASCII_BUTTON_A              3100
#define IDC_ASCII_BUTTON_Z              3190
#define IDC_BUTTON_WEBVIPNEW            3191
#define IDC_BUTTON_LINKTABLE            3192
#define IDC_BUTTON_SHUTDOWN             3193
#define IDC_BUTTON_BACKUP               3194
#define IDC_BUTTON_ABOUT                3195
#define IDC_BUTTON_CONFIG               3196
#define IDC_BUTTON_TOOLS                3197
#define IDC_BUTTON_TRAINMODE            3198
#define IDC_BUTTON_INVENTORY            3199
#define IDC_BUTTON_WEBSITE              3200
#define IDC_BUTTON_REGISTER             3201
#define IDC_BUTTON_SERVERIP             3202
#define IDC_BUTTON_CHANGEPSW            3203
#define IDC_BUTTON_CASHIN               3204
#define IDC_BUTTON_CASHOUT              3205
#define IDC_BUTTON_VIEWVIP_WEB          3206
#define IDC_BUTTON_TABLE_REMARK         3207
#define IDC_BUTTON_EATIN                3208
#define IDC_BUTTON_MAKED                3209
#define IDC_BUTTON_TAINFO               3210
#define IDC_BUTTON_TEMPLATE             3211
#define IDC_BUTTON_CLEANTBL             3212
#define IDC_BUTTON_LANGUAGE             3213
#define IDC_BUTTON_VIPPRICE             3214
#define IDC_BUTTON_NEXTSEAT             3215
#define IDC_BUTTON_ASSEMBLE_TABLE       3216
#define IDC_BUTTON_REMINDDISH_CLASS     3217
#define IDC_BUTTON_CHANGE_PRINT_CLASS   3218
#define IDC_BUTTON_ACTUALPAYED          3219
#define IDC_BUTTON_SEPARATECHK          3220
#define IDC_BUTTON_VIEW_WEBCHK          3221
#define IDC_BUTTON_RESERVE              3222
#define IDC_BUTTON_SYNC                 3223
#define IDC_BUTTON_EXTERNAL             3224
#define IDC_BUTTON_CASHREPORT           3225
#define IDC_BUTTON_DISPLAYSET           3226
#define IDC_CLASS_BUTTON                4000
#define IDC_SLU_BUTTON                  4100
#define IDC_BUTTON_NEXTPAGE             5000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        451
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1120
#define _APS_NEXT_SYMED_VALUE           296
#endif
#endif
